services:
  - type: web
    name: odoo
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: odoo-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: odoo-postgres
          property: port
      - key: DB_USER
        fromDatabase:
          name: odoo-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: odoo-postgres
          property: password
      - key: DB_NAME
        value: odoo

databases:
  - name: odoo-postgres
    databaseName: odoo
    user: odoo
